version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example1234
      MONGO_INITDB_DATABASE: reward

volumes:
  mongodb_data:
    driver: local
