version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example1234
      MONGO_INITDB_DATABASE: reward
    networks:
      local-network:
        ipv4_address: "172.3.0.2"

  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3001:3001"
    env_file:
      - ./apps/gateway/.env.local
    depends_on:
      - mongodb
      - auth
      - event
    networks:
      local-network:
        ipv4_address: "172.3.0.3"

  auth:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3000:3000"
    env_file:
      - ./apps/auth/.env.local
    depends_on:
      - mongodb
    networks:
      local-network:
        ipv4_address: "172.3.0.5"

  event:
    build:
      context: ./apps/event
      dockerfile: Dockerfile
    container_name: event
    ports:
      - "3002:3002"
    env_file:
      - ./apps/event/.env.local
    depends_on:
      - mongodb
    networks:
      local-network:
        ipv4_address: "172.3.0.4"

volumes:
  mongodb_data:
    driver: local

networks:
  local-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.3.0.0/24"
